name: 'Jina Hub Builder'
description: 'Build your Pod into Docker image and share with the community'
env:
   PR_NUMBER:
     description: number of the PR
     default: ${{ github.event.pull_request.number }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
branding:
  icon: 'package'
  color: 'green'
