name: Jina Hub Image Builder
description: Build & test your Pod into Docker image and share with the community
author: Jina AI

outputs:
  success_targets:
    description: Successfully built targets with their paths
  failed_targets:
    description: Failed built targets with their paths
inputs:
  push:
    description: 'if add --push to jina hub build command'
    required: false
    default: 'False'
  dockerhub_username:
    description: 'user name of the Docker registry'
    required: false
  dockerhub_password:
    description: 'the plaintext password of the docker hub'
    required: false
  dockerhub_registry:
    description: 'the URL to the Docker registry'
    required: false
    default: 'https://index.docker.io/v1/'
  mongodb_hostname:
    description: 'the host name of Mongodb Atlas'
    required: false
  mongodb_username:
    description: 'the user name of Mongodb Atlas'
    required: false
  mongodb_password:
    description: 'password of Mongodb Atlas'
    required: false
  mongodb_database:
    description: 'database in Mongodb Atlas'
    required: false
  mongodb_collection:
    description: 'collection in Mongodb Atlas'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.push }}
    - ${{ inputs.dockerhub_username }}
    - ${{ inputs.dockerhub_password }}
    - ${{ inputs.dockerhub_registry }}
    - ${{ inputs.mongodb_hostname }}
    - ${{ inputs.mongodb_username }}
    - ${{ inputs.mongodb_password }}
    - ${{ inputs.mongodb_database }}
    - ${{ inputs.mongodb_collection }}
branding:
  icon: 'package'
  color: 'green'
