name: Jina Hub Image Builder
description: Build & test your Pod into Docker image and share with the community
author: Jina AI
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'package'
  color: 'green'
