name: Jina Hub Image Builder
description: Build & test your Pod into Docker image and share with the community
author: Jina AI

outputs:
  success_targets:
    description: Successfully built targets with their paths
  failed_targets:
    description: Failed built targets with their paths
inputs:
  is_ci:
    description: 'if add --push to jina hub build command'
    required: true
    default: 'False'
  dockerhub_username:
    description: 'user name of the docker registry'
    required: false
  dockerhub_password:
    description: 'the plaintext password of the docker hub'
    required: false
  dockerhub_registry:
    description: 'the URL to the registry'
    required: false
    default: 'https://index.docker.io/v1/'
  mondodb_hostname:
    description: 'hostname of mongodb atlas'
    required: false
  mongodb_username:
    description: 'username of mongodb atlas'
    required: false
  mongodb_password:
    description: 'password of mongodb atlas'
    required: false
  mongodb_database:
    description: 'database in mongodb atlas'
    required: false
  mongodb_collection:
    description: 'collection in mongodb atlas'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.is_ci }}
    - ${{ inputs.dockerhub_username }}
    - ${{ inputs.dockerhub_password }}
    - ${{ inputs.dockerhub_registry }}
    - ${{ inputs.mondodb_hostname }}
    - ${{ inputs.mongodb_username }}
    - ${{ inputs.mongodb_password }}
    - ${{ inputs.mongodb_database }}
    - ${{ inputs.mongodb_collection }}
branding:
  icon: 'package'
  color: 'green'
